// IT Business question bank: 40 TF, 40 MCQ, 20 matching sets (4 pairs each)

export const tfItems = [
  ['ITIL is a framework of best practices for IT service management.', true],
  ['COBIT is primarily a framework for IT governance and management.', true],
  ['IT governance ensures that IT investments are aligned with business strategy and objectives.', true],
  ['A Service Level Agreement (SLA) defines the expected level of service between a provider and a customer.', true],
  ['Change management in ITIL aims to make changes as quickly and informally as possible, with minimal review.', false, 'Change management aims to control changes and manage risk, not skip review.'],
  ['A business case is typically developed to justify the investment in a proposed IT project.', true],
  ['Return on Investment (ROI) measures the financial benefit gained relative to the cost of an investment.', true],
  ['Total Cost of Ownership (TCO) considers only the initial purchase price of an IT asset.', false, 'TCO also includes maintenance, support, training, and disposal costs.'],
  ['A RACI matrix defines who is Responsible, Accountable, Consulted, and Informed for project tasks.', true],
  ['Business Process Reengineering (BPR) involves radically redesigning business processes to improve performance.', true],
  ['IT risk management involves identifying, assessing, and mitigating risks that could affect IT-enabled business objectives.', true],
  ['A Statement of Work (SOW) formally defines the scope, deliverables, and timeline of a project or contract.', true],
  ['Enterprise architecture frameworks like TOGAF help align IT strategy with business goals.', true],
  ['Outsourcing IT functions always eliminates all business risk related to those functions.', false, 'Outsourcing shifts and shares risk but does not eliminate it entirely.'],
  ['A Service Desk in ITIL serves as the single point of contact between users and the IT service provider.', true],
  ['Key Performance Indicators (KPIs) are used to measure progress toward strategic or operational goals.', true],
  ['Business continuity planning is solely the responsibility of the IT department, with no involvement from other business units.', false, 'It requires coordination across the whole organization.'],
  ['IT strategic planning should be developed independently of the overall business strategy.', false, 'IT strategy should align with and support the overall business strategy.'],
  ["A stakeholder is any individual or group with an interest in or influence over a project's outcome.", true],
  ['Change management should always be skipped for emergency changes, regardless of risk.', false, 'Emergency changes still follow an expedited but controlled process.'],
  ['IT service management (ITSM) focuses on designing, delivering, managing, and improving IT services.', true],
  ["A vendor management program helps organizations manage relationships and performance of third-party suppliers.", true],
  ["Governance, Risk, and Compliance (GRC) is an integrated approach to managing an organization's governance, risk, and regulatory compliance.", true],
  ['IT audits are only concerned with financial statements and have no relation to system controls.', false, 'IT audits assess system controls, security, and compliance as well.'],
  ['A project charter formally authorizes a project and grants the project manager authority to use resources.', true],
  ['Agile project management always avoids any planning, relying purely on improvisation.', false, 'Agile still involves planning, just in shorter, iterative cycles.'],
  ['IT service continuity management focuses on ensuring IT services can be restored following a disruption.', true],
  ['Capacity management aims to ensure IT resources are sufficient to meet current and future business demand.', true],
  ['A SWOT analysis examines an organization\'s Strengths, Weaknesses, Opportunities, and Threats.', true],
  ['Digital transformation refers only to replacing paper documents with PDFs.', false, 'It refers to a broader, fundamental change in how technology is used across the business.'],
  ["IT compliance ensures that an organization's IT practices adhere to relevant laws, regulations, and standards.", true],
  ['A steering committee typically provides strategic direction and oversight for major IT initiatives.', true],
  ['Sunk costs should be a primary factor in deciding whether to continue a failing IT project.', false, 'Sunk costs are already spent and should not drive future decisions.'],
  ["Benchmarking compares an organization's processes or performance metrics against industry standards or competitors.", true],
  ['Change advisory boards (CAB) review and approve significant changes before they are implemented in ITIL practice.', true],
  ['Business continuity and disaster recovery planning are identical concepts with no distinction.', false, 'They are related but distinct: BC covers overall operations, DR focuses on IT restoration.'],
  ['A balanced scorecard evaluates organizational performance from multiple perspectives, not just financial ones.', true],
  ['IT procurement involves the process of acquiring goods and services needed to support IT operations.', true],
  ['Shadow IT refers to IT systems or solutions used within an organization without explicit approval from the IT department.', true],
  ["Vendor lock-in refers to a customer's ease of switching to a different vendor without significant cost or disruption.", false, 'Vendor lock-in is the opposite — difficulty switching vendors.'],
]

export const mcqItems = [
  ['Which framework is widely used for IT service management best practices?', ['TOGAF', 'ITIL', 'SWOT', 'RACI'], 1],
  ['What is the primary purpose of a Service Level Agreement (SLA)?', ['Define company holiday schedules', 'Define the expected level and quality of service between provider and customer', 'List employee job descriptions', 'Track marketing campaigns'], 1],
  ['What does COBIT primarily provide a framework for?', ['Software coding standards', 'IT governance and management', 'Graphic design', 'Network cabling'], 1],
  ['What is the main purpose of IT governance?', ['Manage physical office space', 'Ensure IT investments and activities align with business strategy and deliver value', 'Design company logos', 'Schedule employee vacations'], 1],
  ['What does ROI measure?', ['Number of employees in IT', 'The financial return gained relative to the cost of an investment', 'Server uptime percentage', 'Number of support tickets closed'], 1],
  ['What does TCO (Total Cost of Ownership) include beyond the purchase price?', ["Nothing else, it's just the purchase price", 'Costs like maintenance, support, training, and eventual disposal', 'Only shipping costs', "Only the vendor's profit margin"], 1],
  ["In a RACI matrix, what does the 'A' represent?", ['Assigned', 'Accountable', 'Approved', 'Available'], 1],
  ['What is the purpose of a business case in IT project management?', ['Document employee attendance', 'Justify the investment and expected value of a proposed project', 'Define network IP addressing', 'Record server passwords'], 1],
  ['What does a Statement of Work (SOW) typically define?', ['Company mission statement', 'The scope, deliverables, and timeline of a project or contract', 'Employee benefits package', 'Marketing budget'], 1],
  ['Which enterprise architecture framework is commonly used to align business and IT strategy?', ['TOGAF', 'HTML', 'TCP/IP', 'SMTP'], 0],
  ['What is the main goal of a Change Advisory Board (CAB) in ITIL?', ['Approve employee raises', 'Review and approve significant IT changes before implementation', 'Design office layouts', 'Manage payroll'], 1],
  ['What is the role of a Service Desk in ITSM?', ['Sell IT hardware to customers', 'Serve as the single point of contact between users and the IT service provider', "Manage the company's legal contracts", 'Handle physical building security'], 1],
  ['What do Key Performance Indicators (KPIs) measure?', ['Random daily events', 'Progress toward specific strategic or operational goals', 'Only employee attendance', 'Weather conditions'], 1],
  ['What is the purpose of capacity management in ITSM?', ['Reduce the number of employees', 'Ensure IT resources meet current and future business demand', 'Eliminate the need for servers', 'Increase marketing spend'], 1],
  ['What does a SWOT analysis evaluate?', ['Salary, Wages, Overtime, Time-off', 'Strengths, Weaknesses, Opportunities, Threats', 'Servers, Workstations, Operating systems, Terminals', 'Sales, Warehousing, Operations, Transport'], 1],
  ["What is 'shadow IT'?", ['An officially sanctioned backup data center', 'IT systems or solutions used without explicit approval from the IT department', 'A type of encryption', 'A disaster recovery site'], 1],
  ['What is vendor lock-in?', ['The ease of switching vendors at any time', 'A situation where a customer becomes dependent on a vendor with high switching costs', 'A type of firewall', "A vendor's marketing strategy"], 1],
  ['What is the primary purpose of a project charter?', ['Track daily expenses', 'Formally authorize a project and grant the project manager authority over resources', 'List all IT assets', 'Document server configurations'], 1],
  ["Which term describes an organization's integrated approach to governance, risk, and regulatory compliance?", ['ROI', 'GRC', 'SLA', 'KPI'], 1],
  ['What is the goal of business process reengineering (BPR)?', ['Keep processes exactly as they are', 'Radically redesign processes to achieve significant performance improvements', 'Increase paperwork', 'Reduce customer satisfaction'], 1],
  ['What does IT service continuity management primarily focus on?', ['Marketing new products', 'Ensuring IT services can be restored following a disruption', 'Hiring new staff', 'Designing office furniture'], 1],
  ["What is a steering committee's typical role in IT governance?", ['Perform daily system backups', 'Provide strategic direction and oversight for major IT initiatives', 'Write source code', 'Answer help desk tickets'], 1],
  ["Which best describes 'digital transformation'?", ['Simply converting paper files to PDF', "Fundamentally changing how an organization operates and delivers value using digital technology", 'Buying new computers only', "Updating a company's logo"], 1],
  ['What is the purpose of vendor management?', ['Ignore third-party supplier performance', 'Manage relationships, contracts, and performance of third-party suppliers', 'Replace all vendors with in-house staff', 'Set employee salaries'], 1],
  ['What does a balanced scorecard evaluate?', ['Only financial performance', 'Organizational performance across multiple perspectives', 'Only customer complaints', 'Only employee attendance'], 1],
  ['What best describes benchmarking in a business context?', ['Randomly guessing performance targets', 'Comparing processes or metrics against industry standards or competitors', 'Ignoring competitor performance', 'Setting goals with no reference point'], 1],
  ['What is the primary purpose of IT compliance?', ['Maximize profits regardless of regulation', 'Ensure IT practices adhere to relevant laws, regulations, and standards', 'Eliminate all IT policies', 'Reduce staff training'], 1],
  ["In project management, what is a 'stakeholder'?", ['Only the project sponsor', "Any individual or group with an interest in or influence over a project's outcome", 'Only external customers', 'Only the IT department'], 1],
  ['What is the main purpose of change management in ITIL?', ['Implement changes without any review', 'Ensure changes to IT systems are made in a controlled, low-risk manner', 'Prevent all changes from ever occurring', 'Increase system downtime'], 1],
  ['What does an IT audit typically assess?', ['Only marketing effectiveness', 'The effectiveness of IT controls, security, and compliance', 'Employee vacation balances', 'Office supply inventory'], 1],
  ["Which best defines 'IT risk management'?", ['Avoiding all use of technology', 'Identifying, assessing, and mitigating risks to IT-enabled business objectives', 'Ignoring potential threats', 'Purchasing insurance only'], 1],
  ["What is the purpose of a disaster recovery plan in relation to business continuity?", ['Replace the business continuity plan entirely', 'Provide the technical steps to restore IT systems and data after a disruption', 'Increase marketing reach', 'Eliminate the need for backups'], 1],
  ["Which best defines 'outsourcing' in an IT context?", ['Hiring internal staff exclusively', 'Contracting a third party to perform IT functions or services', 'Building all software in-house', 'Avoiding all vendor relationships'], 1],
  ['What is the primary purpose of enterprise architecture?', ['Design physical building layouts', 'Align IT infrastructure and strategy with business goals', 'Manage employee payroll', 'Create marketing materials'], 1],
  ["What does 'sunk cost' refer to in project decision-making?", ['Future costs not yet incurred', 'Money already spent that cannot be recovered, regardless of future decisions', 'Costs that increase with project success', 'A type of insurance'], 1],
  ['Which is a typical output of IT strategic planning?', ['A randomly chosen technology stack', 'A roadmap aligning technology initiatives with business objectives', "A list of employee birthdays", 'A social media calendar'], 1],
  ['What is the primary goal of a service catalog in ITSM?', ['Hide available services from users', 'Provide users a clear list of available IT services and how to request them', 'Track employee attendance', 'Manage physical inventory only'], 1],
  ['Which term describes formally accepting and authorizing a change request within an organization?', ['Change approval', 'Sunk cost analysis', 'Vendor lock-in', 'Shadow IT'], 0],
  ['What is the primary focus of problem management in ITIL, as distinct from incident management?', ['Restoring service as quickly as possible after a single incident', 'Identifying and addressing the root cause of recurring incidents', 'Managing employee schedules', 'Designing new hardware'], 1],
  ['Which best describes governance, risk, and compliance (GRC) software?', ['Tools coordinating governance, risk management, and compliance in one framework', 'A video editing tool', 'A network cabling standard', 'A programming language'], 0],
]

export const matchItems = [
  ['Match each ITIL practice with its focus.', [
    ['Incident management', 'Restoring normal service as quickly as possible'],
    ['Problem management', 'Identifying and resolving root causes of recurring incidents'],
    ['Change management', 'Controlling how changes are made to IT systems'],
    ['Service desk', 'Acting as the single point of contact for users'],
  ]],
  ['Match each governance framework with its focus area.', [
    ['ITIL', 'IT service management best practices'],
    ['COBIT', 'IT governance and management controls'],
    ['TOGAF', 'Enterprise architecture development'],
    ['ISO/IEC 27001', 'Information security management systems'],
  ]],
  ['Match each project management term with its meaning.', [
    ['Project charter', 'Formally authorizes a project and its manager'],
    ['Statement of Work', 'Defines scope, deliverables, and timeline'],
    ['Stakeholder', 'Anyone with interest or influence over the project'],
    ['RACI matrix', 'Clarifies roles as Responsible, Accountable, Consulted, Informed'],
  ]],
  ['Match each financial/business term with its meaning.', [
    ['ROI', 'Financial return relative to investment cost'],
    ['TCO', 'The full cost of owning an asset over its lifetime'],
    ['Business case', 'Justification for a proposed investment or project'],
    ['Sunk cost', 'Money already spent that cannot be recovered'],
  ]],
  ['Match each ITSM concept with its description.', [
    ['SLA', 'Defines expected service levels between provider and customer'],
    ['KPI', 'A measurable value tracking progress toward a goal'],
    ['Service catalog', 'A list of available IT services users can request'],
    ['Capacity management', 'Ensures resources meet current and future demand'],
  ]],
  ['Match each risk/compliance term with its meaning.', [
    ['Risk assessment', 'Evaluating likelihood and impact of potential threats'],
    ['Compliance', 'Adhering to relevant laws, regulations, and standards'],
    ['GRC', 'Integrated approach to governance, risk, and compliance'],
    ['Audit', 'Independent review of controls and processes'],
  ]],
  ['Match each business analysis tool with its purpose.', [
    ['SWOT analysis', 'Examines strengths, weaknesses, opportunities, and threats'],
    ['Balanced scorecard', 'Evaluates performance across multiple perspectives'],
    ['Benchmarking', 'Compares performance against industry standards'],
    ['Gap analysis', 'Identifies the difference between current and desired states'],
  ]],
  ['Match each vendor/sourcing term with its meaning.', [
    ['Outsourcing', 'Contracting a third party to perform business functions'],
    ['Vendor lock-in', 'Difficulty switching providers due to high switching costs'],
    ['Vendor management', 'Overseeing relationships and performance of suppliers'],
    ['Procurement', 'The process of acquiring goods and services'],
  ]],
  ['Match each organizational role with its typical responsibility.', [
    ['Steering committee', 'Provides strategic direction for major initiatives'],
    ['Project manager', 'Plans, executes, and closes projects'],
    ['Change Advisory Board', 'Reviews and approves significant changes'],
    ['Service owner', 'Accountable for the delivery of a specific IT service'],
  ]],
  ['Match each business continuity term with its meaning.', [
    ['Business continuity plan', 'Keeps critical operations running during disruption'],
    ['Disaster recovery plan', 'Restores IT systems and data after a major incident'],
    ['Failover', 'Automatic switch to a backup system'],
    ['Recovery Time Objective', 'Target time to restore a service after disruption'],
  ]],
  ['Match each strategy concept with its meaning.', [
    ['IT strategy', 'A plan aligning technology initiatives with business goals'],
    ['Digital transformation', 'Fundamental change in operations enabled by digital technology'],
    ['Enterprise architecture', 'Structured approach to aligning IT and business goals'],
    ['Business process reengineering', 'Radical redesign of processes for major improvement'],
  ]],
  ['Match each ITIL lifecycle stage with its focus.', [
    ['Service strategy', 'Defining the perspective, position, and plans for services'],
    ['Service design', 'Designing new or changed services'],
    ['Service transition', 'Moving new or changed services into live operation'],
    ['Service operation', 'Managing services on a day-to-day basis'],
  ]],
  ['Match each change-related term with its meaning.', [
    ['Change request', 'A formal proposal to alter a system or process'],
    ['Change approval', 'Formal authorization to proceed with a change'],
    ['Emergency change', 'A change that must be implemented urgently'],
    ['Rollback plan', 'A plan to undo a change if it fails'],
  ]],
  ['Match each performance/measurement term with its definition.', [
    ['KPI', 'A specific, measurable indicator of performance'],
    ['Benchmark', 'A reference point for comparison'],
    ['Metric', 'A quantifiable measure used to track a process'],
    ['Baseline', 'The starting point used to measure progress or change'],
  ]],
  ['Match each term related to IT and organizational structure.', [
    ['Shadow IT', 'Technology used without formal IT department approval'],
    ['CIO', "Executive responsible for an organization's information technology strategy"],
    ['IT steering committee', 'Group overseeing alignment of IT investments with strategy'],
    ['Business analyst', 'Bridges business needs and technical solutions'],
  ]],
  ['Match each procurement/contract term with its meaning.', [
    ['Request for Proposal (RFP)', 'A document soliciting vendor proposals for a solution'],
    ['Contract', 'A legally binding agreement between parties'],
    ['Service Level Agreement', 'Defines expected service quality and responsibilities'],
    ['Statement of Work', 'Details specific deliverables and timelines of an engagement'],
  ]],
  ['Match each organizational change concept with its meaning.', [
    ['Change management (organizational)', 'Structured approach to transitioning people through change'],
    ['Resistance to change', 'Pushback from stakeholders affected by a change'],
    ['Communication plan', 'A strategy for informing stakeholders during a change'],
    ['Training plan', 'Preparing employees with skills for a new process or system'],
  ]],
  ['Match each audit-related term with its meaning.', [
    ['Internal audit', "Conducted by an organization's own staff to assess controls"],
    ['External audit', 'Conducted by an independent third party'],
    ['Audit trail', 'A record of system activities used for review'],
    ['Compliance audit', 'Assesses adherence to laws, regulations, or standards'],
  ]],
  ['Match each business continuity metric with its meaning.', [
    ['Recovery Time Objective (RTO)', 'Maximum acceptable time to restore a service'],
    ['Recovery Point Objective (RPO)', 'Maximum acceptable amount of data loss, measured in time'],
    ['Mean Time to Recovery (MTTR)', 'Average time to restore a system after failure'],
    ['Mean Time Between Failures (MTBF)', 'Average time a system operates before failing'],
  ]],
  ['Match each IT financial term with its meaning.', [
    ['CapEx', 'Capital expenditure for long-term assets'],
    ['OpEx', 'Operational expenditure for day-to-day running costs'],
    ['Depreciation', 'Allocating the cost of an asset over its useful life'],
    ['Budget', 'A financial plan estimating income and expenses over a period'],
  ]],
]
