// System Architecture & Information Security question bank: 40 TF, 40 MCQ, 20 matching sets

export const tfItems = [
  ['The CIA triad in information security stands for Confidentiality, Integrity, and Availability.', true],
  ["A firewall's main purpose is to speed up network traffic regardless of security.", false, 'Its main purpose is filtering traffic based on security rules.'],
  ['Symmetric encryption uses the same key for both encryption and decryption.', true],
  ['Asymmetric encryption uses a public key to encrypt and a different private key to decrypt.', true],
  ['A digital signature can help verify both the authenticity and integrity of a message.', true],
  ['The OSI model has 5 layers.', false, 'The OSI model has 7 layers.'],
  ['In the OSI model, the Transport layer is responsible for end-to-end communication and error recovery.', true],
  ['A VPN creates an encrypted tunnel over a public network to protect data in transit.', true],
  ['Multi-factor authentication relies on only one form of credential, such as a password.', false, 'MFA requires two or more independent factors.'],
  ['A DDoS attack attempts to overwhelm a system with traffic to make it unavailable to legitimate users.', true],
  ['Least privilege means giving users the maximum access possible to simplify administration.', false, 'Least privilege means granting only the minimum access needed.'],
  ['Role-Based Access Control (RBAC) assigns permissions to users based on their role within an organization.', true],
  ['Phishing is a social engineering technique used to trick users into revealing sensitive information.', true],
  ['Patch management involves regularly applying updates to fix known vulnerabilities.', true],
  ['A firewall operates only at the application layer and cannot filter network traffic.', false, 'Firewalls can filter at multiple layers, including network and transport.'],
  ['In a three-tier architecture, the presentation, application/business logic, and data layers are separated.', true],
  ['An Intrusion Detection System (IDS) can actively block malicious traffic in real time by default.', false, 'A standard IDS only detects and alerts; an IPS can actively block traffic.'],
  ['Public key infrastructure (PKI) relies on certificate authorities to issue and validate digital certificates.', true],
  ['Hashing is a reversible process that can be decrypted back into the original plaintext.', false, 'Hashing is a one-way function.'],
  ['A single point of failure is a component whose failure would bring down the entire system.', true],
  ['Load balancers distribute incoming network traffic across multiple servers to improve availability and performance.', true],
  ['Defense in depth relies on a single strong security control instead of multiple layered controls.', false, 'Defense in depth uses multiple layers of security controls.'],
  ['A demilitarized zone (DMZ) sits between an internal trusted network and an untrusted external network.', true],
  ['Zero trust architecture assumes users and devices inside the network perimeter should be trusted by default.', false, 'Zero trust assumes nothing is trusted by default, regardless of location.'],
  ['TLS (Transport Layer Security) is commonly used to secure HTTP traffic as HTTPS.', true],
  ['A vulnerability assessment identifies weaknesses, while penetration testing actively attempts to exploit them.', true],
  ['Availability in the CIA triad refers to ensuring authorized users have reliable access to information when needed.', true],
  ['Data integrity ensures that information remains accurate and unaltered except by authorized actions.', true],
  ['A stateless firewall inspects the context of an entire traffic session before making a decision.', false, 'That describes a stateful firewall.'],
  ['Microservices architecture typically increases the number of network calls compared to a monolithic architecture.', true],
  ['Horizontal scaling means adding more powerful hardware to a single existing server.', false, 'That describes vertical scaling; horizontal scaling adds more servers.'],
  ['In cloud computing, IaaS provides virtualized computing infrastructure such as servers and storage.', true],
  ['SaaS requires the customer to manage the underlying operating system and infrastructure.', false, 'The provider manages the infrastructure and OS in a SaaS model.'],
  ['A security incident response plan should define steps for detection, containment, eradication, and recovery.', true],
  ['Social engineering attacks exploit human psychology rather than purely technical vulnerabilities.', true],
  ['Encryption alone guarantees that a system cannot be breached by any other means.', false, 'Encryption is only one layer of protection among many.'],
  ['A honeypot is a decoy system designed to attract and analyze attacker behavior.', true],
  ['Network segmentation can limit the spread of an attacker who has breached part of a network.', true],
  ['In event-driven architecture, components communicate directly through synchronous, blocking calls only.', false, 'Event-driven architecture typically uses asynchronous events.'],
  ['Business continuity planning aims to ensure critical operations can continue during and after a disruptive event.', true],
]

export const mcqItems = [
  ["What does the 'C' in the CIA triad stand for?", ['Compliance', 'Confidentiality', 'Continuity', 'Control'], 1],
  ['Which OSI layer is responsible for logical addressing and routing?', ['Data Link', 'Network', 'Transport', 'Session'], 1],
  ['Which encryption type uses a pair of public and private keys?', ['Symmetric encryption', 'Asymmetric encryption', 'Hashing', 'Encoding'], 1],
  ['What is the primary function of a firewall?', ['Increase network speed', 'Filter network traffic based on security rules', 'Compress data for storage', 'Balance server load'], 1],
  ['Which best describes multi-factor authentication (MFA)?', ['Using only a password to log in', 'Requiring two or more independent credentials to verify identity', 'Sharing one account among multiple users', 'Encrypting a hard drive'], 1],
  ['What is the purpose of the principle of least privilege?', ['Grant users maximum access to reduce support tickets', 'Grant users only the access necessary for their job', 'Disable all user accounts by default', 'Encrypt all network traffic'], 1],
  ['Which attack type overwhelms a system with traffic to make it unavailable?', ['Phishing', 'Denial-of-Service (DoS)', 'SQL injection', 'Man-in-the-middle'], 1],
  ['Which architecture pattern separates an application into presentation, logic, and data layers?', ['Monolithic architecture', 'Three-tier architecture', 'Peer-to-peer architecture', 'Serverless architecture'], 1],
  ['What does a Public Key Infrastructure (PKI) primarily provide?', ['Free internet access', 'A framework for issuing and managing digital certificates', 'A type of firewall', 'A database backup method'], 1],
  ['What is a key characteristic of a hash function?', ['It is reversible with the right key', 'It produces a fixed-size, one-way output from input data', 'It requires two keys', 'It only works on numeric data'], 1],
  ['Which term describes distributing incoming traffic across multiple servers?', ['Load balancing', 'Network segmentation', 'Sharding', 'Tunneling'], 0],
  ["What does 'defense in depth' refer to?", ['Relying on a single powerful firewall', 'Layering multiple security controls so others still protect if one fails', 'Encrypting data twice', 'Hiring more security staff'], 1],
  ['What is a DMZ in network architecture?', ['A fully trusted internal network segment', 'A network segment isolating external-facing services from the internal network', 'A type of encryption algorithm', 'A backup data center'], 1],
  ['What core assumption does Zero Trust architecture make?', ['Devices inside the network are automatically trusted', 'No user or device should be trusted by default, regardless of location', 'Firewalls are unnecessary', 'Passwords are sufficient for all access'], 1],
  ['What is the main difference between vulnerability assessment and penetration testing?', ['They are identical processes', 'A vulnerability assessment finds weaknesses; penetration testing exploits them', 'Penetration testing only reviews documentation', 'Vulnerability assessment requires no tools'], 1],
  ['Which best describes a stateful firewall?', ['It filters packets with no awareness of session context', 'It tracks the state of active connections to make filtering decisions', 'It only works on wireless networks', 'It cannot inspect encrypted traffic under any configuration'], 1],
  ['Which cloud model gives the customer the most control over the OS and applications while the provider manages hardware?', ['SaaS', 'PaaS', 'IaaS', 'FaaS'], 2],
  ['Which cloud service model provides fully managed, ready-to-use software applications?', ['IaaS', 'PaaS', 'SaaS', 'On-premises hosting'], 2],
  ['What is horizontal scaling?', ["Upgrading a single server's CPU and RAM", 'Adding more servers/instances to distribute load', 'Reducing the number of servers', 'Encrypting server traffic'], 1],
  ['What is vertical scaling?', ['Adding more servers to a cluster', 'Increasing the resources (CPU, RAM) of an existing server', 'Splitting a database across regions', 'Load balancing traffic'], 1],
  ['Which incident response phase focuses on limiting the damage of an ongoing security incident?', ['Detection', 'Containment', 'Eradication', 'Recovery'], 1],
  ['What is a honeypot used for in security?', ['Encrypting sensitive files', 'Attracting and studying attacker behavior in a controlled decoy environment', 'Speeding up network traffic', 'Managing user passwords'], 1],
  ['Which of these is an example of a social engineering attack?', ['Phishing email requesting login credentials', 'Buffer overflow exploit', 'SQL injection', 'Brute-force password cracking'], 0],
  ['What does network segmentation help achieve from a security perspective?', ['Increases the attack surface', 'Limits how far an attacker can move if part of the network is breached', 'Removes the need for firewalls', 'Eliminates the need for encryption'], 1],
  ["Which protocol is commonly used to secure web traffic, forming the 'S' in HTTPS?", ['FTP', 'TLS/SSL', 'SMTP', 'SNMP'], 1],
  ['What is the purpose of business continuity planning?', ['Maximize short-term profit', 'Ensure critical operations can continue during and after a disruption', 'Eliminate the need for backups', 'Replace disaster recovery plans entirely'], 1],
  ["Which best defines 'availability' in the CIA triad?", ['Only authorized users can view data', 'Data remains unaltered', 'Authorized users have reliable, timely access to information and systems', 'Data is encrypted at rest'], 2],
  ['What is the primary risk of a single point of failure in system architecture?', ['It improves redundancy', 'Its failure can bring down the entire system or process', 'It increases scalability', 'It reduces operating costs'], 1],
  ['Which best describes event-driven architecture?', ['Components call each other synchronously and wait for a response', 'Components communicate by producing and reacting to events asynchronously', 'All logic runs in a single process', 'There is no separation between producer and consumer'], 1],
  ['What is the main goal of patch management?', ['Add new unrelated features', 'Regularly apply updates to fix known vulnerabilities and bugs', 'Remove all installed software', 'Disable system logging'], 1],
  ["Which access control model assigns permissions based on a user's job function?", ['Discretionary Access Control (DAC)', 'Role-Based Access Control (RBAC)', 'Mandatory Access Control (MAC)', 'No access control'], 1],
  ['What distinguishes an IDS from an IPS?', ['An IDS actively blocks traffic; an IPS only alerts', 'An IDS detects and alerts on suspicious activity; an IPS can also actively block it', 'They are functionally identical', 'IDS only works on wireless networks'], 1],
  ['Which encryption approach is generally faster and used for encrypting large volumes of data?', ['Asymmetric encryption', 'Symmetric encryption', 'Hashing', 'Steganography'], 1],
  ['What is the purpose of a digital signature?', ['Compress a file', 'Verify the authenticity and integrity of a message or document', 'Speed up network transmission', 'Replace the need for a password'], 1],
  ['In a layered (n-tier) architecture, what is the main benefit of separating layers?', ['It removes the need for testing', 'It improves maintainability and lets layers scale or change independently', 'It guarantees zero downtime', 'It eliminates the need for a database'], 1],
  ['Which is a common goal of a disaster recovery plan?', ['Increase system complexity', 'Restore IT systems and data after a catastrophic event within an acceptable time frame', 'Eliminate the need for backups', 'Prevent all future attacks permanently'], 1],
  ["What is 'least privilege' most closely associated with?", ['Giving admin rights to all employees', "Limiting user access rights to only what's needed for their tasks", 'Removing all access controls', 'Sharing credentials across teams'], 1],
  ['Which of these is a common indicator used in vulnerability scanning?', ['Employee satisfaction scores', 'Known CVEs present in software versions', 'Marketing analytics', 'Sales conversion rate'], 1],
  ["What is the main advantage of microservices over monolithic architecture regarding deployment?", ['Services must all be deployed together', 'Services can be developed, deployed, and scaled independently', 'There is only ever one service', 'It removes the need for APIs'], 1],
  ['Which best describes a Virtual Private Network (VPN)?', ['A public, unencrypted network', 'An encrypted tunnel that extends a private network across a public network', 'A type of firewall rule', 'A physical network cable'], 1],
]

export const matchItems = [
  ['Match each CIA triad element with its meaning.', [
    ['Confidentiality', 'Information is disclosed only to authorized parties'],
    ['Integrity', 'Data is accurate and has not been tampered with'],
    ['Availability', 'Authorized users can access systems when needed'],
    ['Authentication', 'Verifying that a user or system is who it claims to be'],
  ]],
  ['Match each OSI layer with its primary function.', [
    ['Network layer', 'Handles logical addressing and routing'],
    ['Transport layer', 'Provides end-to-end communication and error recovery'],
    ['Data Link layer', 'Handles node-to-node data transfer and MAC addressing'],
    ['Application layer', 'Provides network services directly to end-user applications'],
  ]],
  ['Match each network control with its function.', [
    ['Firewall', 'Filters traffic based on security rules'],
    ['Router', 'Forwards data packets between networks'],
    ['Load balancer', 'Distributes traffic across multiple servers'],
    ['IDS', 'Monitors and alerts on suspicious network activity'],
  ]],
  ['Match each cloud service model with its description.', [
    ['IaaS', 'Provides virtualized servers, storage, and networking'],
    ['PaaS', 'Provides a platform for developing and deploying applications'],
    ['SaaS', 'Delivers fully managed software applications to users'],
    ['FaaS', 'Runs individual functions on demand without managing servers'],
  ]],
  ['Match each encryption concept with its description.', [
    ['Symmetric encryption', 'Uses the same key to encrypt and decrypt'],
    ['Asymmetric encryption', 'Uses a public key to encrypt and a private key to decrypt'],
    ['Hashing', 'Produces a fixed, one-way digest of data'],
    ['Digital signature', 'Verifies the authenticity and integrity of a message'],
  ]],
  ['Match each access control model with its approach.', [
    ['Discretionary (DAC)', 'Resource owners decide who can access their resources'],
    ['Mandatory (MAC)', 'Access is governed by a central authority using security labels'],
    ['Role-Based (RBAC)', "Access is granted based on a user's assigned role"],
    ['Least Privilege', 'Users get only the minimum access needed for their tasks'],
  ]],
  ['Match each attack type with its description.', [
    ['Phishing', 'Tricking users into revealing sensitive information'],
    ['DDoS', 'Overwhelming a system with traffic to deny service'],
    ['Man-in-the-middle', 'Intercepting communication between two parties'],
    ['SQL injection', 'Inserting malicious SQL through an input field'],
  ]],
  ['Match each incident response phase with its focus.', [
    ['Detection', 'Identifying that a security incident has occurred'],
    ['Containment', 'Limiting the spread and impact of the incident'],
    ['Eradication', 'Removing the cause of the incident from the environment'],
    ['Recovery', 'Restoring systems to normal operation'],
  ]],
  ['Match each architecture style with its description.', [
    ['Monolithic', 'A single, tightly coupled deployable application'],
    ['Microservices', 'Independently deployable, loosely coupled services'],
    ['Three-tier', 'Separates presentation, logic, and data layers'],
    ['Event-driven', 'Components communicate through asynchronous events'],
  ]],
  ['Match each scaling concept with its description.', [
    ['Vertical scaling', 'Adding more resources (CPU/RAM) to an existing server'],
    ['Horizontal scaling', 'Adding more servers to distribute load'],
    ['Load balancing', 'Distributing traffic across multiple resources'],
    ['Auto-scaling', 'Automatically adjusting resources based on demand'],
  ]],
  ['Match each security control type with an example.', [
    ['Preventive control', 'A firewall blocking unauthorized traffic'],
    ['Detective control', 'An intrusion detection system alerting on anomalies'],
    ['Corrective control', 'Restoring a system from backup after an incident'],
    ['Deterrent control', 'Warning banners about monitored access'],
  ]],
  ['Match each term with its network security purpose.', [
    ['DMZ', 'Isolates public-facing services from the internal network'],
    ['VPN', 'Creates an encrypted tunnel over a public network'],
    ['Network segmentation', 'Divides a network to limit the spread of an attack'],
    ['Honeypot', 'A decoy system used to study attacker behavior'],
  ]],
  ['Match each resilience term with its focus.', [
    ['Business continuity plan', 'Keeping critical operations running during a disruption'],
    ['Disaster recovery plan', 'Restoring IT systems and data after a major incident'],
    ['Backup', 'A copy of data kept for restoration purposes'],
    ['Failover', 'Automatically switching to a standby system when the primary fails'],
  ]],
  ['Match each authentication factor category with an example.', [
    ['Something you know', 'A password or PIN'],
    ['Something you have', 'A hardware security token or phone'],
    ['Something you are', 'A fingerprint or facial scan'],
    ['Somewhere you are', 'Access allowed only from a specific network location'],
  ]],
  ['Match each assessment type with its purpose.', [
    ['Vulnerability assessment', 'Identifies and prioritizes system weaknesses'],
    ['Penetration testing', 'Actively attempts to exploit weaknesses to test defenses'],
    ['Security audit', 'Reviews compliance with policies and standards'],
    ['Risk assessment', 'Evaluates the likelihood and impact of potential threats'],
  ]],
  ['Match each firewall type with its behavior.', [
    ['Packet-filtering firewall', 'Filters traffic based on IP, port, and protocol rules'],
    ['Stateful firewall', 'Tracks the state of active connections'],
    ['Application-layer firewall', 'Inspects traffic at the application protocol level'],
    ['Next-generation firewall', 'Combines filtering with deep packet inspection and threat intelligence'],
  ]],
  ['Match each PKI component with its role.', [
    ['Certificate Authority', 'Issues and verifies digital certificates'],
    ['Public key', 'Shared openly and used to encrypt data or verify signatures'],
    ['Private key', 'Kept secret and used to decrypt data or create signatures'],
    ['Digital certificate', 'Binds a public key to an identity'],
  ]],
  ['Match each system quality attribute with its meaning.', [
    ['Scalability', 'Ability to handle increased load by adding resources'],
    ['Reliability', 'Ability to consistently perform as expected without failure'],
    ['Availability', 'The proportion of time a system is operational and accessible'],
    ['Maintainability', 'Ease of modifying or repairing the system over time'],
  ]],
  ['Match each risk management term with its meaning.', [
    ['Threat', 'A potential cause of an unwanted incident'],
    ['Vulnerability', 'A weakness that can be exploited by a threat'],
    ['Risk', 'The potential for loss when a threat exploits a vulnerability'],
    ['Mitigation', 'Actions taken to reduce risk to an acceptable level'],
  ]],
  ['Match each data protection method with what it protects against.', [
    ['Encryption at rest', 'Unauthorized access to stored data'],
    ['Encryption in transit', 'Interception of data moving across a network'],
    ['Backup and recovery', 'Data loss from hardware failure or disaster'],
    ['Access control', 'Unauthorized users viewing or modifying data'],
  ]],
]
