// Software Engineering question bank: 40 TF, 40 MCQ, 20 matching sets (4 pairs each)

export const tfItems = [
  ['The Waterfall model allows teams to freely revisit and revise completed phases at any time.', false, 'Waterfall is sequential — each phase is meant to finish before the next begins.'],
  ['Unit testing verifies that individual components of software work as expected in isolation.', true],
  ['Integration testing focuses on validating the interactions between combined modules.', true],
  ['A regression test suite is run to confirm new changes have not broken existing functionality.', true],
  ['In Git, "git commit" uploads local changes to a remote repository.', false, 'That describes "git push". A commit only records changes locally.'],
  ['A merge conflict occurs when Git cannot automatically reconcile differences between two commits.', true],
  ['The DRY principle stands for "Do Repeat Yourself" and encourages code duplication.', false, 'DRY means "Don\'t Repeat Yourself".'],
  ['The Single Responsibility Principle states a class should have only one reason to change.', true],
  ['Code review exists primarily to slow down development without improving code quality.', false, 'Its real purpose is catching defects and sharing knowledge before code merges.'],
  ['Continuous Integration (CI) involves frequently merging code changes into a shared repository with automated builds and tests.', true],
  ['Technical debt refers to the extra cost of quick, easy solutions instead of better, longer-lasting ones.', true],
  ['In Agile, requirements are expected to remain completely fixed once the project starts.', false, 'Agile explicitly embraces changing requirements.'],
  ['A use case diagram in UML is primarily used to model the static structure of classes.', false, 'That is the job of a class diagram; use case diagrams model functional interactions.'],
  ['Refactoring is meant to change the external behavior of code while restructuring its internals.', false, 'Refactoring should never change observable behavior.'],
  ['Black-box testing is performed without knowledge of the internal code structure.', true],
  ['White-box testing examines the internal logic and structure of the code.', true],
  ['A monolithic architecture packages all application functionality into a single deployable unit.', true],
  ['Microservices architecture requires all services to share a single database schema.', false, 'Microservices favor independent data ownership per service.'],
  ['Pair programming involves two developers working together at one workstation.', true],
  ['A sprint in Scrum typically lasts between one and four weeks.', true],
  ['The Product Owner is responsible for maximizing product value and managing the Product Backlog.', true],
  ['Test-driven development (TDD) requires writing production code before writing any tests.', false, 'TDD writes a failing test first, then the code to make it pass.'],
  ['Version control systems can only track changes to text files, not binary files.', false],
  ['A "fork" in Git creates an independent copy of a repository, typically on a hosting platform.', true],
  ['Cyclomatic complexity measures the number of independent paths through a program\'s source code.', true],
  ['Agile discourages any documentation because it values working software over documentation.', false, 'Agile values working software MORE, not documentation NOT AT ALL.'],
  ['A design pattern is a general, reusable solution to a commonly occurring design problem.', true],
  ['The Observer pattern allows an object to notify dependent objects automatically of state changes.', true],
  ['In the SDLC, the maintenance phase occurs before the software is deployed to production.', false, 'Maintenance happens after deployment/release.'],
  ['Smoke testing is a quick set of tests to check if the most crucial functions of a build work.', true],
  ['Static code analysis requires executing the program to detect defects.', false, 'Static analysis inspects source code without running it.'],
  ['A code smell is a symptom that may indicate a deeper problem in the code.', true],
  ['The acronym SOLID includes the Liskov Substitution Principle.', true],
  ['Continuous Deployment automatically releases every change that passes the pipeline to production.', true],
  ['In Kanban, work items are pulled through columns on a board representing workflow stages.', true],
  ['A Scrum product backlog is fixed and can never be reprioritized once created.', false, 'The backlog is a living artifact that is continuously reprioritized.'],
  ['Peer code review can help catch bugs and share knowledge across a development team.', true],
  ['Encapsulation in OOP means exposing all internal data of an object directly to other objects.', false, 'Encapsulation restricts direct access to internals.'],
  ['Polymorphism allows objects of different classes to be treated as objects of a common superclass.', true],
  ['A burndown chart tracks remaining work against time during a sprint.', true],
]

export const mcqItems = [
  ['Which SDLC model is strictly sequential, completing each phase before the next begins?', ['Agile', 'Waterfall', 'Scrum', 'Kanban'], 1],
  ['Which testing level is typically performed first, testing individual functions in isolation?', ['System testing', 'Acceptance testing', 'Unit testing', 'Integration testing'], 2],
  ['Which Git command creates a new branch and switches to it in one step?', ['git branch', 'git checkout -b', 'git merge', 'git clone'], 1],
  ['Which SOLID principle states software entities should be open for extension but closed for modification?', ['Single Responsibility', 'Open/Closed', 'Liskov Substitution', 'Dependency Inversion'], 1],
  ['What is the primary goal of refactoring?', ['Add new features', 'Improve internal structure without changing behavior', 'Fix security vulnerabilities only', 'Increase code size'], 1],
  ['Which Agile ceremony is held daily to synchronize the team\'s work?', ['Sprint Review', 'Sprint Planning', 'Daily Scrum', 'Retrospective'], 2],
  ['Which testing type checks whether software meets business requirements from an end-user view?', ['Unit testing', 'Acceptance testing', 'Static analysis', 'Load testing'], 1],
  ['Which version control operation combines the history of two branches?', ['Clone', 'Merge', 'Fetch', 'Fork'], 1],
  ['What does CI/CD primarily aim to achieve?', ['Manual, infrequent releases', 'Frequent, automated integration and delivery of code', 'Eliminating all testing', 'Avoiding version control'], 1],
  ['Which design pattern restricts a class to a single instance with a global access point?', ['Factory', 'Singleton', 'Observer', 'Adapter'], 1],
  ['Which UML diagram best represents the sequence of interactions between objects over time?', ['Class diagram', 'Sequence diagram', 'Use case diagram', 'Deployment diagram'], 1],
  ['What is "technical debt"?', ['Money owed to software vendors', 'The implied cost of rework from choosing an easy solution now', 'A type of security vulnerability', 'A metric for test coverage'], 1],
  ['In Scrum, who is responsible for removing impediments blocking the team?', ['Product Owner', 'Scrum Master', 'Stakeholder', 'QA lead'], 1],
  ['Which testing approach involves testing without knowledge of internal code structure?', ['White-box testing', 'Black-box testing', 'Unit testing', 'Static testing'], 1],
  ['What does the acronym "DRY" stand for in software engineering?', ['Do Repeat Yourself', "Don't Repeat Yourself", 'Design Rapidly Yearly', 'Debug Regularly Yourself'], 1],
  ['Which architecture style structures an app as small, independently deployable services?', ['Monolithic', 'Microservices', 'Layered', 'Client-server'], 1],
  ['What is the main purpose of a code review?', ['Slow down releases', 'Catch defects and share knowledge before merging code', 'Replace automated testing', 'Increase technical debt'], 1],
  ['Which of these contradicts the Agile Manifesto\'s stated values?', ['Individuals and interactions over processes and tools', 'Comprehensive documentation over working software', 'Customer collaboration over contract negotiation', 'Responding to change over following a plan'], 1],
  ['Which term describes a measurable, functional piece of software delivered at the end of a sprint?', ['Backlog', 'Increment', 'Epic', 'Velocity'], 1],
  ['Which testing type evaluates how a system performs under expected and peak load?', ['Unit testing', 'Performance/load testing', 'Static analysis', 'Smoke testing'], 1],
  ['In Git, what does "git pull" do?', ['Uploads local commits to a remote', 'Fetches and merges changes from a remote repository', 'Deletes a branch', 'Creates a new repository'], 1],
  ['Which principle states subclasses should be substitutable for their base class without breaking the app?', ['Interface Segregation', 'Liskov Substitution', 'Dependency Inversion', 'Open/Closed'], 1],
  ['What is the purpose of a "smoke test"?', ['Exhaustively test every feature', 'Quickly verify critical functionality works after a build', 'Test only the UI', 'Measure code coverage'], 1],
  ['Which of these best describes "pair programming"?', ['Two unrelated teams working separately', 'Two developers working together at one workstation', 'Testing in pairs of environments', 'Running two servers simultaneously'], 1],
  ['Which Scrum artifact is an ordered list of everything needed in the product?', ['Sprint Backlog', 'Product Backlog', 'Burndown Chart', 'Definition of Done'], 1],
  ['Which of these is a characteristic of static code analysis?', ['Requires the program to be running', 'Executes test cases against live data', 'Analyzes source code without executing it', 'Only works on compiled binaries'], 2],
  ['Which metric estimates the number of independent paths through a program?', ['Code coverage', 'Cyclomatic complexity', 'Velocity', 'Burn rate'], 1],
  ['What is the primary benefit of Test-Driven Development (TDD)?', ['Tests are written after deployment', 'Writing tests first drives simpler, verifiable design', 'It removes the need for code review', 'It guarantees zero bugs'], 1],
  ['Which best defines "encapsulation" in object-oriented programming?', ['Exposing all class internals publicly', 'Bundling data and methods while restricting direct access', 'Allowing multiple inheritance', 'Converting classes into functions'], 1],
  ['What does "polymorphism" allow in object-oriented design?', ['Only one class to exist per program', 'Objects of different classes to be treated through a common interface', 'Classes to have no methods', 'Variables to change type only at runtime'], 1],
  ['Which Git command shows differences between the working directory and the last commit?', ['git status', 'git diff', 'git log', 'git stash'], 1],
  ['In the V-Model, what does each development phase correspond to?', ['A marketing milestone', 'A corresponding testing phase', 'A code freeze', 'A deployment window'], 1],
  ['Which term describes reworking code\'s internal structure without changing external behavior?', ['Debugging', 'Refactoring', 'Compiling', 'Deploying'], 1],
  ['What is a "code smell"?', ['A compiler warning only', 'An indicator of a possible deeper problem in the code', 'A type of malware', 'A required comment style'], 1],
  ['Which Agile framework visualizes work using a board with columns like To Do, In Progress, Done?', ['Scrum', 'Kanban', 'Waterfall', 'Spiral'], 1],
  ['What is the purpose of the Sprint Retrospective in Scrum?', ['Demo the increment to stakeholders', 'Reflect on the past sprint and identify process improvements', "Plan the next sprint's backlog", 'Estimate story points'], 1],
  ['Which of the following is an example of a behavioral design pattern?', ['Singleton', 'Observer', 'Factory', 'Adapter'], 1],
  ['What distinguishes continuous deployment from continuous delivery?', ['Changes are manually approved before release', 'Every change that passes automated tests is released automatically', 'Deployment happens only once a year', 'Only hotfixes are automated'], 1],
  ['Which best describes "dependency injection"?', ["Hardcoding a class's dependencies inside it", "Supplying a class's dependencies from an external source", 'Removing all dependencies from a project', 'A type of unit test'], 1],
  ['What is the main goal of acceptance testing?', ['Verify low-level code logic', 'Confirm the system meets business requirements and is ready for release', 'Measure server response time', 'Detect memory leaks'], 1],
]

export const matchItems = [
  ['Match each SDLC phase with its focus.', [
    ['Requirements Analysis', 'Gathering and documenting what the system must do'],
    ['Design', 'Defining the system architecture and components'],
    ['Implementation', 'Writing the actual source code'],
    ['Maintenance', 'Fixing issues and updating the system after release'],
  ]],
  ['Match each testing type with its description.', [
    ['Unit testing', 'Testing individual functions or components in isolation'],
    ['Integration testing', 'Testing interactions between combined modules'],
    ['System testing', 'Testing the complete, integrated system'],
    ['Acceptance testing', 'Validating the system against business requirements'],
  ]],
  ['Match each Git command with its purpose.', [
    ['git clone', 'Creates a local copy of a remote repository'],
    ['git commit', 'Records changes to the local repository'],
    ['git push', 'Uploads local commits to a remote repository'],
    ['git pull', 'Fetches and merges remote changes into the local branch'],
  ]],
  ['Match each SOLID principle with its meaning.', [
    ['Single Responsibility', 'A class should have only one reason to change'],
    ['Open/Closed', 'Open for extension, closed for modification'],
    ['Liskov Substitution', 'Subtypes must be substitutable for their base types'],
    ['Dependency Inversion', 'Depend on abstractions, not concrete implementations'],
  ]],
  ['Match each Agile/Scrum role with its responsibility.', [
    ['Product Owner', 'Manages and prioritizes the product backlog'],
    ['Scrum Master', 'Facilitates the process and removes impediments'],
    ['Development Team', 'Builds the product increment'],
    ['Stakeholder', 'Provides feedback on the product'],
  ]],
  ['Match each design pattern with its purpose.', [
    ['Singleton', 'Ensures a class has only one instance'],
    ['Factory Method', 'Creates objects without specifying the exact class'],
    ['Observer', 'Notifies dependents automatically of state changes'],
    ['Adapter', 'Allows incompatible interfaces to work together'],
  ]],
  ['Match each Scrum artifact with its description.', [
    ['Product Backlog', 'Ordered list of everything needed in the product'],
    ['Sprint Backlog', 'Tasks selected for the current sprint'],
    ['Increment', 'The usable result produced at the end of a sprint'],
    ['Burndown Chart', 'Visual tracker of remaining work over time'],
  ]],
  ['Match each testing technique with its knowledge requirement.', [
    ['Black-box testing', 'Tests functionality without knowledge of internal code'],
    ['White-box testing', 'Tests internal logic and structure of the code'],
    ['Gray-box testing', 'Combines partial internal knowledge with external testing'],
    ['Regression testing', 'Re-tests software after changes to catch new defects'],
  ]],
  ['Match each software architecture style with its trait.', [
    ['Monolithic', 'All functionality bundled into a single deployable unit'],
    ['Microservices', 'Independently deployable, loosely coupled services'],
    ['Layered', 'Organizes code into horizontal responsibility tiers'],
    ['Event-driven', 'Components communicate by producing and consuming events'],
  ]],
  ['Match each version control concept with its meaning.', [
    ['Branch', 'An independent line of development'],
    ['Merge', 'Combines changes from different branches'],
    ['Merge conflict', "Occurs when changes can't be automatically reconciled"],
    ['Fork', 'An independent copy of a repository, often on a hosting platform'],
  ]],
  ['Match each UML diagram with what it models.', [
    ['Class diagram', 'Static structure of classes and relationships'],
    ['Sequence diagram', 'Order of interactions between objects over time'],
    ['Use case diagram', "Functional requirements from a user's perspective"],
    ['Deployment diagram', 'Physical hardware and software deployment layout'],
  ]],
  ['Match each code quality concept with its description.', [
    ['Code smell', 'A surface indicator of a deeper design problem'],
    ['Technical debt', 'Cost of choosing an easy fix over a better long-term solution'],
    ['Cyclomatic complexity', 'Measure of independent paths through code'],
    ['Refactoring', 'Restructuring code without changing its behavior'],
  ]],
  ['Match each CI/CD term with its definition.', [
    ['Continuous Integration', 'Frequently merging and testing code changes'],
    ['Continuous Delivery', 'Keeping code always ready for manual release'],
    ['Continuous Deployment', 'Automatically releasing every passing change'],
    ['Build pipeline', 'Automated sequence of build, test, and deploy steps'],
  ]],
  ['Match each requirement type with an example.', [
    ['Functional requirement', 'The system must allow users to reset their password'],
    ['Non-functional requirement', 'The system must respond within 2 seconds'],
    ['Business requirement', 'The system must increase sales conversions'],
    ['Constraint', 'The system must run on existing legacy hardware'],
  ]],
  ['Match each testing level with when it typically occurs.', [
    ['Unit testing', 'During development, before code is merged'],
    ['Integration testing', 'After modules are combined'],
    ['System testing', 'After the full system is assembled'],
    ['User acceptance testing', 'Just before release, by end users'],
  ]],
  ['Match each Agile ceremony with its purpose.', [
    ['Sprint Planning', 'Decide what work will be done in the sprint'],
    ['Daily Scrum', "Synchronize the team on daily progress"],
    ['Sprint Review', 'Demonstrate the increment to stakeholders'],
    ['Sprint Retrospective', "Reflect and improve the team's process"],
  ]],
  ['Match each OOP concept with its meaning.', [
    ['Encapsulation', 'Bundling data and methods, restricting direct access'],
    ['Inheritance', 'A class acquiring properties of another class'],
    ['Polymorphism', 'Treating different classes through a common interface'],
    ['Abstraction', 'Hiding complex details behind a simple interface'],
  ]],
  ['Match each software metric with what it measures.', [
    ['Code coverage', 'Percentage of code exercised by tests'],
    ['Velocity', 'Amount of work a team completes per sprint'],
    ['Defect density', 'Number of defects per unit of code size'],
    ['Lead time', 'Time from work start to delivery'],
  ]],
  ['Match each software licensing type with its trait.', [
    ['Open-source license', 'Source code is freely available to view and modify'],
    ['Proprietary license', 'Vendor retains exclusive rights to the source code'],
    ['Copyleft license', 'Derivative works must be distributed under the same license'],
    ['Freeware', "Free to use but source code isn't necessarily available"],
  ]],
  ['Match each deployment strategy with its description.', [
    ['Blue-green deployment', 'Two identical environments swap traffic for near-zero downtime'],
    ['Canary deployment', 'New version rolled out to a small subset of users first'],
    ['Rolling deployment', 'Instances updated gradually one at a time'],
    ['Rollback', 'Reverting to a previous stable version after a failed release'],
  ]],
]
